MN-Script-Team/DHS-PRISM-Scripts

Shared Functions Library/PRISM Functions Library.vbs

It's now check_for_PRISM, and includes the same end_script parameter all
the kids are talking about.

Switched PRISM_check_function to match MAXIS

---

Shared Functions Library/PRISM Functions Library.vbs

Added Custom Function. write_value_and_transmit enables the script writer to take two lines and merge them into one. SO, instead of an 
EMWriteScreen value, row, col
transmit
The user can CALL write_value_and_transmit(value, row, col).

New Custom Function

---

Script Files/NOTES/NOTES - COURT ORDER REQUEST.vbs

This is a CAAD note script that notes date court order was requested, place/person requested from, request method, court file number, order type, and worker signature.  It will then navigate to CAWT and create a worklist to remind you if the court order was received.  It does not save the worklist, in case you want to add additional notes in the worklist first before saving and also a date must be added.
I originally pull requested this at the training in March, but have since added the auto-filling of the PRISM case number.  I think this should be good to go!

NOTES - COURT ORDER REQUEST.vbs

---

Script Files/NOTES/NOTES - WAIVER OF PERSONAL SERVICE.vbs

This is a CAAD note script that will CAAD note when the waiver of personal service is signed by the CP.  It uses CAAD code D5010 and by using that CAAD code a worklist is automatically created.
This is another script I had originally pull requested at training in March, but have since added the logic to populate the PRISM case number when in a PRISM case.  I think it is done and working great!

NOTES - WAIVER OF PERSONAL SERVICE.vbs

---

Script Files/ACTIONS/ACTIONS - FEE SUPPRESSION OVERRIDE.vbs

This script navigates to the 2nd panel of CAST and manually overrides the cost recovery fee to be 1 year later than today's date. This is used to suppress the fee on cases that are NPA, but have MNSure open and the MNSure interface is not yet working.

Wrightcountykaren feesuppression

---

Script Files/BULK/BULK - EVALUATE NOCS.vbs

Creation of the BULK - EVALUATE NOCS.vbs script.
This script performs the following actions...
Navigates to USWT to grab the worker ID and name. It presents that information in a dialog, allowing the user to use this script on any authorized caseload. Once the worker has determined the caseload to work on, the script builds a multi-dimensional array of all cases with a D0800 worklist item. It then navigates to CALI to determine the program code. It then navigates to CAST to determine if the case is full service. It then navigates to CATH to determine the program code change date. It then navigates to GCSC to determine if the case is coop or non-coop.
The script then dumps all the information into an Excel file to present to the worker. For each case in the array, the script presents a …

Bulk nocs create

---

Shared Functions Library/PRISM Functions Library.vbs

this function is duplicated in the MAXIS FuncLib

Removed "run_another_script" from the PRISM FuncLib

---

Script Files/BULK/BULK - E4111 WORKLIST SCRUBBER.vbs

This script navigates to USWT and filters for the E4111 Worklist, which notifies the case worker that the driver's license payment plan on the case is continuingly delinquent.  The script selects a worklist to navigate to PAPD, and then navigates to ENFL and filters for DLS records.  The script then searches the records for the case number and reads the DL status for the case.  If the status is ACT, that is, the NCP's driver's license is already suspended, the script returns to the USWT and purges the worklist.  If the DL status is anything else, the script does not purge the worklist.  The script then moves to the next E4111 worklist until all E4111 worklists have been evaluated.

E4111 Worklist Scrubber

---

Script Files/ACTIONS/ACTIONS-NCP LOCATE

This script would be used to help a worker navigate through PRISM locate screens.  It provides a reminder to check other non-PRISM systems and website as well.  If the user requests it will generate locate questionnaires, add credit bureau CAAD (header), generate full credit bureau notice, add a worklist for future locate review.  It will add a CAAD regarding the locate review.

Create ACTIONS-NCP LOCATE

---

ALL SCRIPTS.vbs

remove 10 scripts from Dakota regular users. non pay, prorate, client contact, intake doc received, mes financial, non pay month 1-4, pay or report, quarterly review, payment plan review, transfer case bulk.

Removing DAKOTA from specific scripts

---

Shared Functions Library/PRISM Functions Library.vbs

Blip: `save_cord_doc` and `send_text_to_DORD` have been depreciated.
* `save_cord_doc` should be replaced with `write_value_and_transmit` when the FuncLib bridge goes live.
* `send_text_to_DORD` has been replaced with a new function called `write_variable_in_DORD`. It does the same thing (just a name change).

Resolved #413: depreciated save_cord_doc and send_text_to_DORD

---

Script Files/ACTIONS/ACTIONS - RECORD IW INFO.vbs

This record income withholding information script allows the user to enter a CAAD note, create a worklist, or display in a message box the withholding amount broken down by pay frequency.  Anoka County uses this script when sending out an IW notice, and the CAAD note and worklist options are automatically selected.  The worklist is set for follow up after 30 days.  If the user de-selects the CAAD note and worklist options, the output will display in the message box.

Resolves #473

---

Script Files/BULK/BULK - FAILURE POF RSDI DFAS.vbs

Resolves #364:  Code is completely re-worked.  Script populates an excel spreadsheet of data for those cases that have the E0014 worklist and makes note of the employer on PAPL and NCSU (NCID).  A dialog is displayed for the user to examine the cases one-by-one and determine if the employer/payor of funds is the same and should be purged, or should not purged.  If the payor of funds is DFAS, US Treasury or Social Security, the script will default to purging the worklist.  The user makes the final decision and those worklists that the user indicates should be purged will be purged.

Resolves #364

---

Script Files/ACTIONS/ACTIONS - SEND F0104 DORD MEMO.vbs

BLIP: This script modification adds safeguards to make sure the user doesn't get suspended from PRISM.

Resolves #551 -- adding check_for_PRISM

---

Script Files/ACTIONS/ACTIONS - COURT PREP WORKSHEET.vbs

BLIP: This update removes the function `go_to` from the Court Prep Worksheet with a function already in FuncLib (`write_value_and_transmit`).

Resolves #594 -- Removing `go_to` from Court Prep Worksheet

---

notes/pay-or-report.vbs

BLIP: This update adds left padding on the case number dialog for NOTES - PAY OR REPORT to reduce the goofification of the display.

Resolves #578 - Fixing Case Number Dialog

---

notes/pay-or-report.vbs

BLIP: Correcting the dialog so it displays the values in the variables instead of the variable names.

Resolves #649 -- updating dialog to undo an oopsy

---

actions/case-transfer.vbs

This was causing the err_msg to not run when the team was not 3 characters long.

#701: removed the : from the team variable

---

actions/cola.vbs

BLIP: This update corrects a syntax that is preventing the script from running. I have also corrected a spelling error on the word override (see line 122).

RE: #723 - correcting syntax error

---

bulk/list-generator---cali.vbs

BLIP: This update replaces `IF buttonpressed = 0 then stopscript` with `cancel_confirmation`. Additionally, the script can now stop after the second dialog is run.

RE: 722 adding cancel_confirmation

---

actions/returned-mail.vbs

This update to the Returned Mail action script should address the reported error that occurs if the case the user is working on is not stored in the globals.

Issue #734

---

actions/case-transfer.vbs

#786 Added additional language to the last message box to remind case worker to complete the transfer of the case.
"Success! The case has been transferred and CAAD noted. Please complete any additional necessary actions per your county's case transfer process."
Tested locally

#786 Updated last message box

---

notes/maintaining-county.vbs

I updated the dialog box to have the option to enter worker's name, county, and phone number. When this is entered into CAAD, I have updated the script to write this info on one line.
I changed the word "Reviewing County" to "Responding County" on the dialog box.
I lastly added the option to have the user be able to add a CAWT note to follow up with maintaining county request.

Updated Request for Enhancements #759

---

actions/affidavit-of-service-by-mail-docs.vbs

Corrected the 2 button selections that were mixed up in the script.  When Case Financial Summary - CAFS is selected, the script will print and select this correctly in DORD and same with the Affidavit of Default and ID selection.

Fixed Bug/Issue #802
