MN-Script-Team/DHS-PRISM-Scripts

Script Files/NAV/NAV - CAWT.vbs
Script Files/REDIRECT - NAV - CAWT.vbs

Created Redirect and NAV, then adding CAWT to power pad

Added cawt

---

Script Files/ACTIONS scripts/ACTIONS - Update Worker Signature.vbs

giving the CS peeps the script to create workersig.txt

Adding ACTIONS - Update Worker Signature

---

Script Files/NOTES/NOTES - DATE OF THE HEARING (JUDICIAL).vbs

Converted droplist to dynamic from array

---

Shared Functions Library/PRISM Functions Library.vbs

Thinking of an option explicit future...

Added beta agency handling and some variable declaration

---

Script Files/NOTES/NOTES - PAYMENT PLAN REVIEW.vbs

100% complete.  Would like auto filling for Beg date, Total Due, Delinquency Amount to make this really cool.

Create NOTES - PAYMENT PLAN REVIEW.vbs

---

Script Files/ACTIONS/ACTIONS - PRORATE SUPPORT.vbs
sample funclib call.vbs

This is a new script that can be used to calculate prorate child support for a number of days for a particular month.  This script is very generic and can be used for any obligation and on any case.

ACTIONS - PRORATE SUPPORT

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

Added ACTIONS - PRORATE SUPPORT to Actions Main Menu

Update to ACTIONS main menu

---

NOTES - INTAKE DOCS RECEIVED.vbs

I think I added in the part about needing to be in a PRISM case, but you need you to look over.  I also added the date in.  The only thing that might be missing, is if there is no case in my globals, and I manually enter in a valid prism case number into my dialog box, it does not navigate to that case and write the note??  Am I still missing something??  Thanks!

NOTES - INTAKE DOCS RECEIVED.vbs

---

Script Files/NOTES/NOTES - SOP INVOICE.vbs

This is a CAAD noting script that notes information about service of process invoices.

NOTES - SOP INVOICE.vbs

---

Script Files/NOTES/NOTES - CSENET Info.vbs

This is a script that will copy info from INTD and paste it into a new CAAD note.  The only time we are running into issues, is when the text uses all of the lines in INTD, it will not paste nicely into CAAD lines.  Need to be able to word wrap, or just not use the script when the INTD screen has verbiage in paragraph form.  Thanks!

NOTES - CSENET Info.vbs

---

Script Files/NOTES/NOTES - ROP DETAIL.vbs

This is a CAAD note script that will note the dates and place a ROP was signed.  It will also message box if the CP or the NCP was under 18 yrs old when the ROP was signed.  It will CAAD note if one of the parties was under 18 yrs when the ROP was signed.

NOTES - ROP DETAIL.vbs

---

Shared Functions Library/PRISM Functions Library.vbs

This has the PRISM FuncLib loading the MAXIS FuncLib to take advantage of the shared scripts, and also has additional PFs and the new Word doc updating functions.

Updated PRISM FuncLib

---

Script Files/NOTES/NOTES - MES FINANCIAL DOCS SENT.vbs

Use this one, there was one small typo that is now fixed.

NOTES - MES FINANCIAL DOCS SENT.vbs

---

Script Files/BULK/BULK - CALI TO EXCEL.vbs

Added a dialog box to check if you'd like the script to pull data from CAFS and enter it into the Excel document.
(Checking this box while in your actual caseload will make the script take a lot longer because it has to load every single CAFS screen... BUT ITS COOL THOUGH!)

Update BULK - CALI TO EXCEL.vbs

---

Script Files/ACTIONS/ACTIONS - DDPL CALCULATOR.vbs

This script will calculate payments issued on DDPL for a chosen time period and display the total in a message box.  This script is not county specific.

DDPL calculator

---

Script Files/ACTIONS/ACTIONS - EST DORD NPA DOCS.vbs

This script prints the Estb Dord docs (financial statements, waivers, Important Statement of Rights and the NCP Notice of Liability) for a NPA case for each party, enters the CAAD note and enters the work list due date for the forms on CAWT.

Create ACTIONS - EST DORD NPA DOCS.vbs

---

ACTIONS/ACTIONS - ESTB DORD DOCS FOR PA CASE.vbs
ESTB DORD DOCS FOR PA CASE.vbs

This script prints the DORD docs for the parties (financial statements, waivers, Important Statement of Rights, NCP Authorization to Collect), puts a CAAD note on the case,  and enters the due date on CAWT for the forms.

Create ESTB DORD DOCS FOR PA CASE.vbs

---

Script Files/REDIRECT - BULK.vbs

creating BULK redirect. This allows the button on the powerpad to access the BULK main menu.

Create REDIRECT - BULK.vbs

---

sample funclib call.vbs

Robert - here is the pull request

Case Bulk Transfer

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

The user enters a list of worker numbers or position numbers. The script then creates a dialog for each worker and the user enters up to 15 cases for that worker and the script transfers those cases.
If the user enters an invalid worker or position number, the script delivers a message box informing you of that.

Create bulk case transfer

---

Script Files/BULK/BULK - MAIN MENU.vbs

Adding BULK - CASE TRANSFER to the main menu.

Update bulk main menu

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

The script was not properly set up to handle 8-digit worker IDs but it is now...hopefully.

Update BULK - CASE TRANSFER

---

Script Files/ACTIONS/ACTIONS - FIND NAME ON CALI.vbs
Script Files/NOTES/NOTES - CLIENT CONTACT.vbs

Includes:
* Update to BULK - CASE TRANSFER

Pushing MASTER to BETA

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

Update BULK - CASE TRANSFER.vbs

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

One of these days, this will be correct...

Update case transfer

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

Sorry about blowing up your email.

Pushing yet another fix from MASTER to BETA

---

Shared Functions Library/PRISM Functions Library.vbs

This function converts the yyddmm to dd/mm/yyyy in PALC and PAPL screens

Update PRISM Functions Library.vbs

---

Script Files/BULK/FAILURE POF RSDI DFAS

This script will auto purge worklist  E0014 Failure to Withhold POF for payments received from RSDI and DFAS

FAILURE POF RSDI DFAS

---

Script Files/BULK/BULK - CP COMPANION CASE FINDER.vbs

New script.
Builds a list of companion cases from CALI based on the CP's MCI.

Create bulk cp companion case finder

---

Script Files/BULK/BULK - NCP COMPANION CASE FINDER.vbs

New script that builds a list in Excel of companion cases according to NCP MCI.

Create bulk ncp companion case finder

---

Script Files/BULK/BULK - FAILURE POF RSDI DFAS

updating the script...
* Added documentation
* Removed duplicate functions
* Simplified formatting for easier debugging

Update BULK - FAILURE POF

---

Script Files/BULK/BULK - MAIN MENU.vbs

(1) Adding CP Companion Case Finder to main menu
(2) Adding NCP Companion Case Finder to main menu

Updating bulk main menu

---

Script Files/ACTIONS/ACTIONS - PALC CALCULATOR.vbs

Revision to PALC calculator to improve efficiency.

Update ACTIONS - PALC CALCULATOR.vbs

---

Script Files/BULK/BULK - FAILURE POF RSDI DFAS.vbs

Update BULK - FAILURE POF RSDI DFAS.vbs

---

Script Files/BULK/BULK - FAILURE POF RSDI DFAS.vbs

This script checks PAPL for current payments from DFAS, Social Security, US Dept of Treasury and purges E0014 worklist if meets criteria.

Tested and Working!!

---

Script Files/ACTIONS/ACTIONS - UNREIMBURSED UNINSURED DOCS.vbs

This generates the 3 Dord Documents for cp or ncp to request uninsured/unreimbursed med/dental expenses.  You do have to select the correct legal heading manually.

Create new file

---

Script Files/ACTIONS/ACTIONS - IW CALCULATOR.vbs

This script will calculate biweekly, weekly, and semimonthly payments.  It pulls monthly accrual but you can change the amount.  You pick if you wants 20% added for arrears collection or add your own amount.  It is just a quick way to calculate amounts.

IW CALCULATOR

---

Script Files/NOTES/NOTES - IW CAAD CAWT.vbs

This is for when you are sending an new or amended IW notice.  It creates a CAAD note that includes employer, new or amended IW, and includes, monthly, biweekly, semimonthly, and weekly amounts.  It gives a option for a CAWT note to be added 30 days in the future to check that iw started and adds the monthly, biweekly, semimonthly, and weekly amounts.

IW caad cawt

---

Script Files/ACTIONS/ACTIONS - NON PAY.vbs

This is a new script that provides the following options to the user:
- send a DORD memo document that is a generic non-pay letter, (optional) purge worklist E0002, and add an E9685 (Delinquency notice sent) caad note
- send a notice of payment plan non-compliance, (optional) purge worklist E4111

Create ACTIONS - NON PAY.vbs

---

Script Files/NOTES/NOTES - CASE TRANSFER.vbs

This is a script that will transfer a case and also CAAD note details of the transfer.

NOTES - CASE TRANSFER.vbs

---

Script Files/BULK/BULK - EVALUATE NOCS.vbs

Resolves #195 - issues with purging the worklist.

Update BULK - EVALUATE NOCS.vbs

---

Script Files/ACTIONS/ACTIONS - IW CALCULATOR.vbs

Update to ACTIONS - IW Calculator to add the option for adding a worklist.  If the user does not add a worklist, the IW calculator displays results in a message box.

Update ACTIONS - IW CALCULATOR.vbs

---

Script Files/BULK/BULK - REVIEW QW INFO.vbs

Having the script run twice to make sure it purges all appropriate worklists.

Update BULK - REVIEW QW INFO.vbs

---

Script Files/NOTES - Adjustments

Creates a CAAD note for adjustments made by the worker to what obligation(s), the total amount adjusted and a description as to why and how the adjustment was made.

Create NOTES - Adjustments

---

Script Files/NOTES/NOTES - ADJUSTMENTS.vbs

Updated the dialog box size and layout and added error messages.

Update NOTES - ADJUSTMENTS.vbs

---

Script Files/ACTIONS/ACTIONS - UNREIMBURSED UNINSURED DOCS.vbs

updated script to fix error reported.

Update ACTIONS - UNREIMBURSED UNINSURED DOCS.vbs

---

Shared Functions Library/PRISM Functions Library.vbs

Updated CAAD note functions to only work when variable is filled.

Updated CAAD note functions

---

Script Files/NOTES/NOTES - INTAKE DOCS RECEIVED.vbs

Blip - added err msg handling, resolves issue #238

Fixed err msg handling, resolves #238

---

Script Files/ACTIONS/ACTIONS - CP NAME CHANGE.vbs

blip: Updated CPDE last name, updates alias with a "Y", modifies CAAD note M1000 CP NAME ADDED / CHANGED  with new name, reason for change and workers signature.
Resolves issues #265

Resolves issue #265: New action script CP NAME CHANGE

---

Script Files/NOTES/NOTES - E-FILING.vbs

Resolves #263
New E-Filing Caad note. I will do documentation tomorrow!  Please make a button on the power pad for this :-)

Create NOTES - E-FILING.vbs

---

Script Files/NOTES/NOTES - IW CAAD CAWT.vbs

updating the decimal place and fixing duplicate pull request done in error.

Update NOTES - IW CAAD CAWT.vbs

---

Script Files/SHARING-IS-CARING/ACTIONS - EMC DORD Docs.vbs

This script gives user quick access to dord documents for emancipation.  The script selects a child within 3 months of turning 18 on one specific case.  The user can send emancipate letter to cp, emancipation letter to ncp, and emancipation follow up to cp.

Create ACTIONS - EMC DORD Docs.vbs

---

Script Files/SETTINGS - GLOBAL VARIABLES.vbs

Updating global variables to include lists for child support magistrates and judges.  Also added clarifying comments and modified the county attorney listings to demonstrate what the list should look like, rather than simply displaying Anoka county data.

Update SETTINGS - GLOBAL VARIABLES.vbs

---

Shared Functions Library/BULK - Emancipation Worklist Scrubber.vbs
Shared Functions Library/BULK -EMANCIPATION WORKLIST SCRUBBER.vbs

I updated this script as requested.  This script looks for work list M0935 on a specific caseload.  The script verifies there is a child that will be turning 18 years old within 3 months on each case.  It verifies there is EMC language on suod.  If there is no EMC language then a note is added to the M0935 work list that further review is needed.  If EMC language is found then script sends dord doc f0300 and f0302 and purges the worklist.  Minimal testing has been done.

Create BULK - Emancipation Worklist Scrubber.vbs

---

Script Files/NOTES/NOTES - E-FILING.vbs

Added an edit box for E-Service Details.

Update NOTES - E-FILING.vbs

---

Script Files/NOTES/NOTES - E-FILING.vbs

Reverts MN-CS-Script-Team/PRISM-Scripts#290

Revert "Update NOTES - E-FILING.vbs"

---

Script Files/NOTES/NOTES - FRAUD REFERRAL.vbs

New CAAD noting script that details fraud referral made. Uses CAAD code M0010. Also give worker option to add a worklist to follow up on the referral.
Resolves #295

Create NOTES - FRAUD REFERRAL.vbs

---

Script Files/NOTES/NOTES - WAIVER OF PERSONAL SERVICE.vbs

Removed em writescreen that was causing a weird glitch in the date location. Should work now!

Update NOTES - WAIVER OF PERSONAL SERVICE.vbs

---

ALL SCRIPTS.vbs

Updates to the E4111 bulk scripts as the file names were switched around.

Update ALL SCRIPTS.vbs

---

ALL SCRIPTS.vbs

prorate support, intake doc's received, mes financial, pay or report, and quarterly review.

Removing DAKOTA from Specific Scripts (5)

---

ALL SCRIPTS.vbs

adding back the No pay report but removing pay or report for DAKOTA.

ADD one and REMOVE DAKOTA from specific scripts

---

Script Files/NOTES/NOTES - PAY OR REPORT.vbs

This has been run in Anoka for months with great success.

Resolves #151 -- Auto determining and auto filling pay & report dates

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs

Simplifying access to instructions in SIR.

Resolves #337

---

Script Files/NOTES/NOTES - SOP INVOICE.vbs

Resolves #342 . Added a Substitute Service checkbox.

Update NOTES - SOP INVOICE.vbs

---

Script Files/NOTES/NOTES - GENETIC TESTING INVOICE.vbs

Resolves #345
Blip:  This script will caad note the details of a genetic testing invoice.

Create NOTES - GENETIC TESTING INVOICE.vbs

---

sample funclib call.vbs

Resolves #331 - update to contact

Resolves #331

---

Script Files/ACTIONS/ACTIONS - CASE TRANSFER.vbs

Removed 2 lines of code that were causing the single case transfer dialog to pop up and run twice.

Update ACTIONS - CASE TRANSFER.vbs

---

Script Files/NOTES/NOTES - PAY OR REPORT.vbs

Adding additional fields Court File Number and County Attorney Case Number to worklists and CAAD note.

Resolves #360

---

Script Files/ACTIONS/ACTIONS - SEND F0104 DORD MEMO.vbs

Added spell check functionality to the script.

Resolves #362

---

Script Files/NOTES/NOTES - INVOICES.vbs

Combined the Genetic Testing invoice and the SOP invoice under 1 notes script titled "Invoices"  Power pad Button has been added.  Will modify directions tomorrow!

Create NOTES - INVOICES.vbs

---

Script Files/NOTES/NOTES - INTAKE DOCS RECEIVED.vbs

Removed "app fee" from dialog and script, as the app fee is no longer relevant.

Update NOTES - INTAKE DOCS RECEIVED.vbs

---

Script Files/ACTIONS/ACTIONS - FEE SUPPRESSION OVERRIDE.vbs

This script has been updated allow users to manual add date for fee suppression and to choose a standard caad note or create their own.  #375

Update ACTIONS - FEE SUPPRESSION OVERRIDE.vbs

---

Script Files/ACTIONS/ACTIONS - EST DORD NPA DOCS.vbs

This is an updated script that will print the DORD docs for both parties when starting a new establish action on a NPA case. It prints the Financial Statements, Waivers, Important Statement of Rights and the NCP Authorization letter. It writes a CAAD note of sending forms to parties and the CAWT note to track the return of the forms.

Update ACTIONS - EST DORD NPA DOCS.vbs

---

Script Files/ACTIONS/ACTIONS - ESTB DORD DOCS FOR PA CASE.vbs

This is an updated script that will print the DORD docs for both parties when starting a new establish action on a PA case. It prints the Financial Statements, Waivers, Important Statement of Rights & the NCP Notice of Liability. It writes a CAAD note of sending forms to parties and the CAWT note to track the return of the forms.

Update ACTIONS - ESTB DORD DOCS FOR PA CASE.vbs

---

Script Files/NOTES/NOTES - PAY OR REPORT.vbs

Resolves #374 - fixing issues with this script including PRISM case number auto-fill if run from a case-based screen, and adding attorney name in worklist text.

Resolves #374

---

Script Files/ACTIONS/ACTIONS - SEND F0104 DORD MEMO.vbs

Resolves #384 - bug fix for error message when sending to both parties.

Resolves #384

---

ALL SCRIPTS.vbs

Kallista updated the file name, I'm just fixing the menu.

Resolved #387: file name is updated

---

Script Files/NOTES/NOTES - INVOICES.vbs

Issue #411
Added a 3 option in the drop to include "General Invoice"; copied the coding from the other invoice options so it would follow by doing a CAAD note with the info. .
Thanks,
Jodi

NOTES - INVOICES.vbs

---

Script Files/SETTINGS - GLOBAL VARIABLES.vbs

Per #425, will evaluate each script that loads Word Docs and modify them
to use this path.

Resolved #12: there is now a word_documents_folder_path in GlobVar

---

README.md

Will adjust when we move to MN-Script-Team for sure.

Resolved #396: draft README is in place

---

ALL SCRIPTS.vbs
Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs
Script Files/UTILITIES/UTILITIES - MAIN MENU.vbs

It's been removed from ALL SCRIPTS and the main menu scripts. Now all scripts are available for all staff on master branch.

Resolved #446: removed "agencies_that_use" functionality

---

Script Files/ACTIONS/ACTIONS - EMPLOYMENT VERIFICATION.vbs

This still needs a button. 
I also added it this a new pull request, when it should have been resolving an issue - #394.
SORRY!

#394: Update ACTIONS - EMPLOYMENT VERIFICATION.vbs

---

Script Files/NOTES/NOTES - QUICK CAAD.vbs

It will now check for PRISM prior to running (this prevents
password-outs).

Resolved #485: added PRISM check functionality

---

Script Files/ACTIONS/ACTIONS - NON PAY.vbs

Here is the updated non-pay script, which includes Word documents (see zip file in the #465 issue), used by Anoka County.  Further modifications may be necessary before this script is rolled out for use by other counties...

Resolves #465

---

ALL SCRIPTS.vbs

Resolves #473 - add to all scripts file

---

Script Files/ACTIONS/ACTIONS - INTAKE.vbs

I have additional code:
```vb.net
'THE SCRIPT--------------------------------------------------------------------------------------------------------------------------------
'Opens the Dialog
Dialog Establisment_case_initiation_dialog
'Connecting to BZ
EMConnect ""
CALL navigate_to_prism_screen("CAST")
EMReadScreen PRISM_case_number, 13, 4, 8
EMReadScreen CP_name, 20, 6, 12
EMReadScreen NCP_name, 20, 7, 12
'Checks to make sure we are in Prism
CALL check_for_Prism (true)
Set objWord = CreateObject("Word.Application")
objWord.Visible = True
'STARTS WITH THE DOCS SENT TO THE CP---------------------------------------------------------------------
'Sends word doc for child care expenses, need the document file path here
'If daycare_checkbox = checked then
'CALL word_doc_open("", objWord, …
```

#451: added establishment dialog

---

Script Files/ACTIONS/ACTIONS - EMPLOYMENT VERIFICATION.vbs

Job end dated and term reason have been added.

Update ACTIONS - EMPLOYMENT VERIFICATION.vbs

---

Script Files/ACTIONS/ACTIONS - NON PAY.vbs

Corrects issues #509
Moved part of the dialog box so the word do not overlap

Update ACTIONS - NON PAY.vbs

---

Script Files/ACTIONS/ACTIONS - SEND F0104 DORD MEMO.vbs

This resolves issue #386.
Adds printing the doc.

Update ACTIONS - SEND F0104 DORD MEMO.vbs

---

ALL SCRIPTS.vbs
Script Files/NOTES/NOTES - CONTEMPT HEARING.vbs
Script Files/SETTINGS - GLOBAL VARIABLES.vbs

this was a Stearns County Custom script that our County Attorneys wanted us to use after contempt hearings so they all look the same and include the same information. Makes a CAAD Note. 
Adding this in case other counties would also like to use it. 
Thanks!

Resolves #454

---

Script Files/ACTIONS/ACTIONS - NON PAY.vbs

I added the following info to the NON-PAY memo:  Amount of last payment, date of last payment, amount of arrears, and the website for making payments online.  
The option to export to Word would need to be enhanced if counties want to use the Word doc option for the "Send CP Initial Contempt Ltr"

 Resolves #98

---

Script Files/ACTIONS/ACTIONS - CASE TRANSFER.vbs

This is JUST the ACTIONS - CASE TRANSFER script.  The bulk case transfer piece has been removed.

Actions - Case Transfer - Resolves #460

---

Script Files/ACTIONS/ACTIONS - RETURNED MAIL.vbs

This is a new returned mail actions script. Will work on button and documentation next!!  
Resolves #350

ACTIONS - RETURNED MAIL script - Resolves #350

---

ALL SCRIPTS.vbs
Script Files/BULK/BULK - CASE TRANSFER.vbs

BLIP: Adding BULK case transfer to repo and ALL scripts file.

Resolves #527 

---

Script Files/NOTES/NOTES - MOD CAAD NOTE - CONTACT CHECKLIST.vbs

'GATHERING STATS----------------------------------------------------------------------------------------------------
name_of_script = "NOTES - MOD CAAD NOTE - CONTACT CHECKLIST.vbs"
start_time = timer
STATS_counter = 1
STATS_manualtime = 300
STATS_denomination = "C"
'END OF STATS BLOCK-------------------------------------------------------------------------------------------------
'LOADING FUNCTIONS LIBRARY FROM GITHUB REPOSITORY===========================================================================
IF IsEmpty(FuncLib_URL) = TRUE THEN	'Shouldn't load FuncLib if it already loaded once
IF run_locally = FALSE or run_locally = "" THEN	   'If the scripts are set to run locally, it skips this and uses an FSO below.
IF use_master_branch = TRUE THEN			   'If the default_directory is …

Resolves Issue with worker_signature

---

Script Files/ACTIONS/ACTIONS - NON PAY.vbs

Fixed the misspelled word from arreas  to arrears.

Resolves #538

---

Script Files/SETTINGS - GLOBAL VARIABLES.vbs

Resolved #540: GlobVar will now UCASE the beta_users list when comparing

---

Script Files/SETTINGS - GLOBAL VARIABLES.vbs

BLIP: Added boolean variable in order for agencies to determine if SQL is being used to collect their data.

Resolved # 546 Added using_SQL_database variable

---

Script Files/ACTIONS/ACTIONS - AFFIDAVIT OF SERVICE BY MAIL DOCS.vbs

#463 Fixed legal heading bug by changing from a message box to a dialog box to remind user to select correct legal heading for document.  Added error message for dialog box if required information correctly entered.

Update ACTIONS - AFFIDAVIT OF SERVICE BY MAIL DOCS.vbs

---

Script Files/ACTIONS/ACTIONS - RETURNED MAIL.vbs

Yay! It will now REGL if the case number doesn't match the entered case
number. I also tweaked a few dialog things for clarity sake. Yay!

Resolved #550: returned mail bug is resolved finally!

---

Script Files/ACTIONS/ACTIONS - RETURNED MAIL.vbs

BLIP: Moving the CAAD noting functionality around so the script ALWAYS case notes the address change.

Resolves #559 -- Hopefully -- Updating CAAD Noting for Returned Mail

---

actions/court-prep-worksheet.vbs

BLIP: This update removes a custom function with functionality that functions functionally identical to a custom function already in FuncLib.

Resolved #575 -- Updating functions in Court Prep Worksheet

---

notes/csenet-info.vbs

DHS-PRISM-Scripts/notes/csenet-info.vbs - has spelling error #602

---

utilities/external-resources.vbs

BLIP: This script gives agency super users the ability to dynamically build a menu of external resources.

Resolves #604 -- building dynamic external resources

---

~complete-list-of-scripts.vbs

BLIP: Update to the Complete List of Scripts so the two Un/Un docs are showing up in the ACTIONS menu."

Resolves #598

---

agency-custom/How to use this folder and script.vbs
agency-custom/source/agency-custom.vbs
locally-installed-files/~globvar.vbs

#616: need to test

---

calculators/prorate-support.vbs

I switched the "Ok" and "Cancel" button on the dialog box.

Resolves #618: Switched the "Ok" and "Cancel" buttons

---

nav/maxis-screen-finder.vbs

Updated "case_number" to "MAXIS_case_number" to fix the bug in this script. I've tested a few different MAXIS case numbers and the script seems to flow properly now.

Resolves #624: Updated function "MAXIS_case_number"

---

actions/court-prep-worksheet.vbs

BLIP: This update consolidates five custom functions into one for to make it work goodly.

resolves #594 -- updating functionality in court prep

---

notes/hearing-notes.vbs

added "paternity" to the hearing type drop down list

#633: hearing notes - added Paternity to expro drop down list

---

notes/court-order-request.vbs

672: added E-Filed as a dropdown option for requested via, and added signature date to order type.

#672: Added E-Filed as dropdown option

---

actions/income-verification.vbs

BLIP: This script update addresses an issue with a dialog name/call discrepancy as well as an EMWriteScreen discrepancy on PALC.

RE: #676 #677 #678 -- Updates to ACTIONS - INCOME VERIFICATION

---

actions/income-verification.vbs

BLIP: This pull request replaces emwritescreen with write_date on PALC.

RE: #678 Adding write_date function

---

actions/income-verification.vbs

BLIP: This update adds err_msg handling and write_date to Income Verification.

RE #678 -- adding write_date and polishing Income Verif

---

bulk/review-qw-info.vbs

Blip: Re-wrote the logic of this script as the previous version was prone to skipping matches.  Also modified script to produce spreadsheets for user reference.

Fix for #181

---

index.html
issuelist.html
js/changelog-reader.js

#599: adding issue list tracking

---

notes/case-initiation-docs-received.vbs

Removed worker_signature from DIM.

#694: removed worker_signature from DIM

---

notes/maintaining-county.vbs

This is a new script makes a CAAD note when a county is requesting or responding to changing maintaining county.

#662: Maintaining County Script ready for testing

---

locally-installed-files/~globvar.vbs

Adding the changelog_enabled variable to Global Variables so counties can select their option for thi feature.

#704 ChangeLog Option added to Global Variables

---

actions/cola.vbs

#694, was missing a ")" on the change log script line 49.

#694: added missing parentheses

---

notes/arrears-management-review.vbs

Added the options for the supervisor to approve or deny the AMPP request

#675 Added Supervisor options

---

notes/iw-caad-cawt.vbs

#694: removed worker sig from DIM from this script

#694: removed worker_sig from DIM

---

index.html
js/changelog-reader.js

See commits for details. Basically: you can now filter by date.

#599: almost done with this beast

---

~complete-list-of-scripts.vbs

Adding the button to use the script for E0002

#720 Adding the button

---

notes/maintaining-county.vbs

So user can save the caad note themselves if they want to change anything.

#736: removed transmit from CAAD note

---

locally-installed-files/~globvar.vbs

BLIP: This update add a list of supervisors for the agency and a constant that determines whether the user should have additional functionality.

RE: 721 - Adding supervisor users to globvar

---

actions/interview-information-sheet.vbs

Fix for the Format Currency error message.  #760

See Issue #760 - Interview Information Sheet bug fix

---

instructions.html

Pushing correction to correctly parse in the data from github .vbs files to load into documentation.

Fixed issue with IE parsing documentation data

---

actions/send-f0104-dord-memo.vbs

BLIP: Added error handling to ensure that a recipient is selected, also added error handling to make sure script gets into DORD.
Fixes #770 and #762

Adding error handling and do loop

---

utilities/favorites-list.vbs
~complete-list-of-scripts.vbs

#636 should now be accessible from the main menu.
Also, close #717 already. Those nav scripts have been long gone.

#636: adding favorites list to the complete list

---

notes/hearing-notes.vbs

#746 
tested this and seems to be working.

#746 Added Enter Date in Dialog

---

~complete-list-of-scripts.vbs

#728
Added to the list of Note scripts.

#728 mets-referral-attempted pull request

---

actions/send-f0104-dord-memo.vbs

Update to add check_for_PRISM(false) to ensure users don't accidentally time out.

See Issue #791

---

actions/non-pay.vbs

See Issue #793

---

actions/enforcement-intake.vbs
actions/establishment-dord-docs---npa.vbs
actions/establishment-dord-docs---pa.vbs
actions/generic-enforcement-intake.vbs
actions/income-verification.vbs
actions/sanction.vbs
actions/send-f0104-dord-memo.vbs
actions/unreimbursed-uninsured-returned-docs.vbs
bulk/list-generator---cali.vbs
bulk/list-generator---no-pay.vbs
bulk/review-pay-plan---dl-is-suspended.vbs
calculators/palc.vbs
notes/case-initiation-docs-received.vbs
notes/client-contact.vbs
notes/contempt-hearing.vbs
notes/mes-financial-docs-sent.vbs
utilities/external-resources.vbs

This will help when converting VBScript to Python!

Resolves #815: TODO comment adds across the project
